### ISSUE TITLE
Gui Buttons not working after changing page back and forth

### ISSUE THREAD

**Issue by NyCodeGHG** [bluefireoly/KSpigot#15]
When I switch the page via the [gotoPage function](https://github.com/bluefireoly/KSpigot/blob/68ba031fe020ac745b9234fc5e74d6031736fc44/src/main/kotlin/net/axay/kspigot/gui/GUIPageChange.kt#L39) and I switch back, things like buttons aren't working anymore.

![image](https://rice.by.devs-from.asia/l4ERYFnZNj.gif)

**Comment by bluefireoly** [comment]
That is probably the reason why the internal function was internal (lol).

**Comment by NyCodeGHG** [comment]
hahaha

**Comment by NyCodeGHG** [comment]
Is there another way how i could change the page without the use of pageChanger()? Or maybe a way to provide an onClick lambda and decide if it should change the page or not.

**Comment by bluefireoly** [comment]
Why exactly can't you just use the `pageChanger` element?

**Comment by NyCodeGHG** [comment]
As you maybe have seen in the gif. I want to execute something different when you do a right click on the item. I only want to change the page when the user clicks with the left mouse button.

**Comment by NyCodeGHG** [comment]
I did a little bit testing and the same thing is happening when using pageChanger

**Comment by NyCodeGHG** [comment]
I fixed it. I was using a wrong function somewhere. It was not related to KSpigot.
